title: SAP Team
description: Directorio de Usuarios y Consultores SAP
logo: /assets/img/sap-team.png
baseurl: "/u"
url: "https://consultoria-sap.github.io"
lang: es
show_downloads: false
google_analytics:

# Theme
remote_theme: pages-themes/minimal@v0.2.0

# Exclusiones
exclude:
  - /temp/readme.md
  - /_data/readme.md
  - readme.md

# Collections
collections:
  usuarios:
    output: true
    permalink: /:path/
    sort_by: order


# Otras configuraciones que no tocar√© regularmente

# Plugins
plugins:
- jekyll-remote-theme
- jemoji

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : America/Argentina/Buenos_Aires

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# ini - Los siguientes no pueden cambiarse -ini
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# fin - Los que no pueden cambiarse -fin
